language: python
python:  
    - 3.4
    - 3.6
    - 3.7-dev
install: python3 -m pip install -r requirements.txt
script: python3 -m pytest 

after_success:
    - python3 -m pip install pytest-cov codecov
    - python3 -m pytest --cov=./
    - codecov
